version: '3.5'
services:

  revealjs:
    image: mypresentation
    container_name: mypresentation
    ports:
      - "3000:3000"
    build:
      context: .
      dockerfile: Dockerfile_dev
    volumes:
      - type: bind
        source: ./index.html
        target: /app/index.html
      - type: bind
        source: ./main.js
        target: /app/main.js
      - type: bind
        source: ./favicon.svg
        target: /app/favicon.svg
      - type: bind
        source: ./public
        target: /app/public
