version: '3.5'
services:

  revealjs:
    image: revealjs
    container_name: revealjs
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:5000"
    restart: unless-stopped
